### ISSUE TITLE
Skip "Train the model"

### ISSUE THREAD

**Issue by ZziTaiLeo** [jonepatr/lets_face_it#3]
Is "Train the model" necessary? I just wanted to run this program ,then I skipped this part. The rest of the installation is displayed as normal, but theJson returned by docker is {"detail":"Not Found"}

**Comment by jonepatr** [comment]
Hi, as the model is not provided in this repo currently, you have to first train the model in order to use the inference part. But I will look in to if I can share the final model from the paper as well, so that you don't have to train the model to use this repo.
